# bulk mail / ESP providers
# these should prefer SCORE over hard DENY

sendgrid.net
emsmtp.us
mailchimp.com
amazonses.com
sparkpostmail.com
emarsys.net
constantcontact.com
mailgun.org
mandrillapp.com
