# domains that must never be auto-denied
#
# Format: domain|level|type|comment
#
# level: 
# 1 = keine automatische DENY-Regel
# 2 = keine DENY-Regel, SCORE bevorzugen
# 3 = stark geschützt, keine DENY-Regel, besonders vorsichtig bewerten
#
##############################################################

kleinanzeigen.de|2|marketplace|classifieds platform
dhl.de|2|logistics|parcel service
reichelt.de|2|shop|electronics retailer
fedex.com|2|logistics|parcel service
ipfire.org|3|project|trusted project
pollin.de|2|shop|electronics retailer
paypal.com|3|payment|trusted payment provider
google.com|3|platform|trusted platform
youtube.com|3|platform|trusted platform
openai.com|3|platform|trusted platform
telekom.de|3|isp|mail provider
gog.com|2|shop|games platform
github.com|3|dev|development platform
amazon.de|1|shop|trusted retailer
amazon.com|1|shop|trusted retailer
microsoft.com|2|platform|trusted vendor
