.TH "src Directory Reference" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaccount\&.cc\fP"
.br
.ti -1c
.RI "file \fBaccount\&.hh\fP"
.br
.ti -1c
.RI "file \fBapop\&.cc\fP"
.br
.ti -1c
.RI "file \fBapop\&.hh\fP"
.br
.ti -1c
.RI "file \fBconnection\&.hh\fP"
.br
.ti -1c
.RI "file \fBfeedback\&.cc\fP"
.br
.ti -1c
.RI "file \fBfeedback\&.hh\fP"
.br
.ti -1c
.RI "file \fBfilter\&.cc\fP"
.br
.ti -1c
.RI "file \fBfilter\&.hh\fP"
.br
.ti -1c
.RI "file \fBgetopt\&.c\fP"
.br
.ti -1c
.RI "file \fBgetopt\&.h\fP"
.br
.ti -1c
.RI "file \fBgetopt1\&.c\fP"
.br
.ti -1c
.RI "file \fBmailfilter\&.cc\fP"
.br
.ti -1c
.RI "file \fBmailfilter\&.hh\fP"
.br
.ti -1c
.RI "file \fBmd5\&.h\fP"
.br
.ti -1c
.RI "file \fBmd5c\&.c\fP"
.br
.ti -1c
.RI "file \fBpop3\&.cc\fP"
.br
.ti -1c
.RI "file \fBpop3\&.hh\fP"
.br
.ti -1c
.RI "file \fBpreferences\&.cc\fP"
.br
.ti -1c
.RI "file \fBpreferences\&.hh\fP"
.br
.ti -1c
.RI "file \fBprotocol\&.cc\fP"
.br
.ti -1c
.RI "file \fBprotocol\&.hh\fP"
.br
.ti -1c
.RI "file \fBscore\&.hh\fP"
.br
.ti -1c
.RI "file \fBsocket\&.cc\fP"
.br
.ti -1c
.RI "file \fBsocket\&.hh\fP"
.br
.in -1c
