.TH "account.hh" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
account.hh
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'defines\&.hh'\fP
.br
\fC#include 'protocol\&.hh'\fP
.br
\fC#include 'pop3\&.hh'\fP
.br
\fC#include 'apop\&.hh'\fP
.br
\fC#include 'connection\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAccount\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
