.TH "account.cc" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
account.cc
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <typeinfo>\fP
.br
\fC#include 'account\&.hh'\fP
.br
\fC#include 'pop3\&.hh'\fP
.br
\fC#include 'apop\&.hh'\fP
.br
\fC#include 'preferences\&.hh'\fP
.br
\fC#include 'feedback\&.hh'\fP
.br
\fC#include 'mailfilter\&.hh'\fP
.br
\fC#include 'connection\&.hh'\fP
.br
\fC#include 'socket\&.hh'\fP
.br
\fC#include 'defines\&.hh'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBint_to_string\fP (int)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBmailbox_status\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "string int_to_string (int val)"

.SH "Variable Documentation"
.PP 
.SS "int mailbox_status\fC [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
