.TH "apop.hh" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apop.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'pop3\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAPOP\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
