.TH "apop.cc" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apop.cc
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include 'apop\&.hh'\fP
.br
\fC#include 'feedback\&.hh'\fP
.br
\fC#include 'defines\&.hh'\fP
.br
\fC#include 'mailfilter\&.hh'\fP
.br
\fC#include <strings\&.h>\fP
.br
\fC#include 'md5\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
