.TH "APOP" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
APOP
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <apop\&.hh>\fP
.PP
Inherits \fBPOP3\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBlogin\fP (\fBconst\fP char *usr, \fBconst\fP char *pass, \fBconst\fP unsigned int enc) \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "bool APOP::login (\fBconst\fP char * usr, \fBconst\fP char * pass, \fBconst\fP unsigned int enc) const\fC [virtual]\fP"

.PP
Reimplemented from \fBPOP3\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
