.TH "feedback.cc" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
feedback.cc
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'feedback\&.hh'\fP
.br
\fC#include 'preferences\&.hh'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
