.TH "filter.cc" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filter.cc
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <regex\&.h>\fP
.br
\fC#include 'filter\&.hh'\fP
.br
\fC#include 'mailfilter\&.hh'\fP
.br
\fC#include 'preferences\&.hh'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
