.TH "filter.hh" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filter.hh
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <regex\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFilter\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCASE_DEFAULT\fP   REG_ICASE"
.br
.ti -1c
.RI "#define \fBCASE_SENSITIVE\fP   0"
.br
.ti -1c
.RI "#define \fBCASE_INSENSITIVE\fP   REG_ICASE"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CASE_DEFAULT   REG_ICASE"

.SS "#define CASE_INSENSITIVE   REG_ICASE"

.SS "#define CASE_SENSITIVE   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
