.TH "option" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
option
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <getopt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBhas_arg\fP"
.br
.ti -1c
.RI "int * \fBflag\fP"
.br
.ti -1c
.RI "int \fBval\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int* option::flag"

.SS "int option::has_arg"

.SS "char* option::name"

.SS "int option::val"


.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
