.TH "POP3" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
POP3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pop3\&.hh>\fP
.PP
Inherits \fBProtocol\fP\&.
.PP
Inherited by \fBAPOP\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBlogin\fP (\fBconst\fP char *, \fBconst\fP char *, \fBconst\fP unsigned int) \fBconst\fP"
.br
.ti -1c
.RI "bool \fBlogout\fP (void) \fBconst\fP"
.br
.ti -1c
.RI "int \fBremove_msg\fP (\fBconst\fP unsigned int) \fBconst\fP"
.br
.ti -1c
.RI "int \fBstatus\fP (void) \fBconst\fP"
.br
.ti -1c
.RI "int \fBscan\fP (void) \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "bool POP3::login (\fBconst\fP char * usr, \fBconst\fP char * pass, \fBconst\fP unsigned int enc) const\fC [virtual]\fP"

.PP
Implements \fBProtocol\fP\&.
.PP
Reimplemented in \fBAPOP\fP\&.
.SS "bool POP3::logout (void) const\fC [virtual]\fP"

.PP
Implements \fBProtocol\fP\&.
.SS "int POP3::remove_msg (\fBconst\fP unsigned int num) const\fC [virtual]\fP"

.PP
Implements \fBProtocol\fP\&.
.SS "int POP3::scan (void) const\fC [virtual]\fP"

.PP
Implements \fBProtocol\fP\&.
.SS "int POP3::status (void) const\fC [virtual]\fP"

.PP
Implements \fBProtocol\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
