.TH "preferences.hh" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
preferences.hh
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'defines\&.hh'\fP
.br
\fC#include 'socket\&.hh'\fP
.br
\fC#include 'filter\&.hh'\fP
.br
\fC#include 'score\&.hh'\fP
.br
\fC#include 'account\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPreferences\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
