.TH "protocol.cc" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
protocol.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'connection\&.hh'\fP
.br
\fC#include 'protocol\&.hh'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
