.TH "protocol.hh" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
protocol.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'connection\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProtocol\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPROTOCOL_POP3\fP   2"
.br
.ti -1c
.RI "#define \fBPROTOCOL_APOP\fP   4"
.br
.ti -1c
.RI "#define \fBSSL_C\fP   4096"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PROTOCOL_APOP   4"

.SS "#define PROTOCOL_POP3   2"

.SS "#define SSL_C   4096"

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
