.TH "Score" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Score
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <score\&.hh>\fP
.PP
Inherits \fBFilter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBscore\fP (void) \fBconst\fP"
.br
.ti -1c
.RI "void \fBset_score\fP (int)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBscr\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int Score::score (void) const"

.SS "void Score::set_score (int)"

.SH "Member Data Documentation"
.PP 
.SS "int Score::scr\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
