.TH "Size_score" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Size_score
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <score\&.hh>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBscore\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int Size_score::score"

.SS "int Size_score::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
