.TH "socket.hh" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socket.hh
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <csignal>\fP
.br
\fC#include 'connection\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSocket\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_BYTES\fP   512"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_BYTES   512"

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
