.TH "socket.cc" 3 "Sun Sep 4 2022" "Version 0.8.9" "mailfilter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socket.cc
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <csignal>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include 'defines\&.hh'\fP
.br
\fC#include 'mailfilter\&.hh'\fP
.br
\fC#include 'feedback\&.hh'\fP
.br
\fC#include 'socket\&.hh'\fP
.br
\fC#include 'protocol\&.hh'\fP
.br
\fC#include 'preferences\&.hh'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for mailfilter from the source code\&.
